### ISSUE TITLE
Sending Data from Child process to main process

### ISSUE THREAD

**Issue by gs-akhan** [gs-akhan/cssdocs#2]
Stuck with Sending array's and objects from child process to parent process, so this data can be sent out to client for generating reports

Thanks

**Comment by gs-akhan** [comment]
@gs-rbarman probably want to look into this..

**Comment by gs-akhan** [comment]
@gs-rbarman  problem solved.
I am writing to a file from child process and reading from main process. This works perfectly.

We will change this if we find a better way in future

So closing this..

**Comment by gs-rbarman** [comment]
Fantastic man!
